# -*- coding: utf-8 -*-
"""DroneLog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TG3KhHEFxvyx_m22I1bDUl8OHFKX11D
"""

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

df = pd.read_csv('DroneLog.csv')

df.head()

df.columns = df.columns.str.strip()
df = df.dropna(how='all').copy()

num_cols = [
    'Max Carry Weight (kg)',
    'Actual Carry Weight (kg)',
    'Altitude (meters)',
    'Flight Duration (minutes)',
    'Distance Flown (km)',
    'Battery Remaining (%)',
    'GPS Accuracy (meters)',
    'Wind Speed (m/s)'
]

for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')

df['Flight Date'] = pd.to_datetime(df['Flight Date'], errors='coerce')

# Remove duplicate records. This also removes repeats like D249 and
# records that are identical except for Drone ID.
key_cols = [c for c in df.columns if c != 'Drone ID']
df = df.drop_duplicates(subset=key_cols)

# Invalid / suspicious values
df.loc[df['Actual Carry Weight (kg)'] < 0, 'Actual Carry Weight (kg)'] = np.nan
df.loc[df['Altitude (meters)'] > 1000, 'Altitude (meters)'] = np.nan   # D516 = 8444
df.loc[df['Wind Speed (m/s)'] > 20, 'Wind Speed (m/s)'] = np.nan       # obvious outlier
df = df[df['Battery Remaining (%)'].isna() | df['Battery Remaining (%)'].between(0, 100)]

# Flag overweight flights instead of deleting them
df['Overweight'] = df['Actual Carry Weight (kg)'] > df['Max Carry Weight (kg)']

print(df.shape)
display(df[['Drone ID', 'Flight Status', 'Overweight', 'Battery Remaining (%)']].head())

"""3) Use completed, valid flights for battery analysis
Aborted or unexpectedly landed flights may have different battery behavior, so analyze completed flights separately.
"""

analysis = df[
    (df['Flight Status'] == 'Completed') &
    df['Flight Duration (minutes)'].notna() &
    df['Battery Remaining (%)'].notna()
].copy()

print(analysis.shape)
display(analysis.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

sns.set_theme(style='whitegrid')
pd.set_option('display.max_columns', None)

corr_cols = [
    'Battery Remaining (%)',
    'Flight Duration (minutes)',
    'Distance Flown (km)',
    'Actual Carry Weight (kg)',
    'Altitude (meters)',
    'Wind Speed (m/s)'
]

corr = analysis[corr_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Correlation with Battery Remaining')
plt.show()

display(corr['Battery Remaining (%)'].sort_values())

features = [
    'Flight Duration (minutes)',
    'Distance Flown (km)',
    'Actual Carry Weight (kg)',
    'Altitude (meters)',
    'Wind Speed (m/s)'
]

for col in features:
    plt.figure(figsize=(8, 5))
    sns.scatterplot(
        data=analysis,
        x=col,
        y='Battery Remaining (%)',
        hue='Drone Model',
        alpha=0.65
    )
    sns.regplot(
        data=analysis,
        x=col,
        y='Battery Remaining (%)',
        scatter=False,
        color='black',
        line_kws={'linewidth': 2}
    )
    plt.title(f'Battery Remaining vs {col}')
    plt.show()

model_summary = (
    analysis
    .groupby('Drone Model')
    .agg(
        n=('Battery Remaining (%)', 'size'),
        battery_mean=('Battery Remaining (%)', 'mean'),
        battery_std=('Battery Remaining (%)', 'std'),
        duration_mean=('Flight Duration (minutes)', 'mean'),
        distance_mean=('Distance Flown (km)', 'mean'),
        payload_mean=('Actual Carry Weight (kg)', 'mean'),
        altitude_mean=('Altitude (meters)', 'mean'),
        wind_mean=('Wind Speed (m/s)', 'mean')
    )
    .sort_values('battery_mean')
)

display(model_summary)

import statsmodels.api as sm
import statsmodels.formula.api as smf

model_df = analysis[[
    'Battery Remaining (%)',
    'Flight Duration (minutes)',
    'Distance Flown (km)',
    'Actual Carry Weight (kg)',
    'Altitude (meters)',
    'Wind Speed (m/s)',
    'Drone Model'
]].dropna().rename(columns={
    'Battery Remaining (%)': 'Battery',
    'Flight Duration (minutes)': 'Duration',
    'Distance Flown (km)': 'Distance',
    'Actual Carry Weight (kg)': 'Payload',
    'Altitude (meters)': 'Altitude',
    'Wind Speed (m/s)': 'Wind',
    'Drone Model': 'Drone_Model'
})

formula = 'Battery ~ Duration + Distance + Payload + Altitude + Wind + C(Drone_Model)'

ols = smf.ols(formula, data=model_df).fit()
print(ols.summary())

model_df_std = model_df.copy()

for col in ['Duration', 'Distance', 'Payload', 'Altitude', 'Wind']:
    model_df_std[col] = (
        model_df_std[col] - model_df_std[col].mean()
    ) / model_df_std[col].std()

ols_std = smf.ols(formula, data=model_df_std).fit()
print(ols_std.summary())

coefs = ols_std.params.drop('Intercept').sort_values()
display(coefs)

from statsmodels.stats.outliers_influence import variance_inflation_factor

X = model_df[['Duration', 'Distance', 'Payload', 'Altitude', 'Wind']].copy()
X = sm.add_constant(X)

vif = pd.DataFrame({
    'feature': X.columns,
    'VIF': [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
})

display(vif)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

X = pd.get_dummies(
    model_df.drop(columns='Battery'),
    drop_first=True
)
y = model_df['Battery']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
pred = rf.predict(X_test)

print('R2:', r2_score(y_test, pred))
print('MAE:', mean_absolute_error(y_test, pred))

importances = (
    pd.Series(rf.feature_importances_, index=X.columns)
    .sort_values(ascending=False)
)

display(importances.head(20))

plt.figure(figsize=(10, 6))
sns.barplot(
    x=importances.head(20).values,
    y=importances.head(20).index
)
plt.title('Random Forest Feature Importance')
plt.xlabel('Importance')
plt.show()



# Filter for the most common large drone that carries varying payloads
crop_master = util_df[util_df['Drone Model'] == 'CropMaster'].copy()

# Re-bin just for this drone
crop_master['util_bin'] = pd.cut(
    crop_master['payload_utilization'],
    bins=[-np.inf, 75, 85, 90, 95, np.inf],
    labels=['<75%', '75-85%', '85-90%', '90-95%', '>95%']
)

crop_summary = crop_master.groupby('util_bin', observed=False).agg(
    n=('Battery Remaining (%)', 'size'),
    mean_duration=('Flight Duration (minutes)', 'mean'),
    mean_battery=('Battery Remaining (%)', 'mean'),
    failure_rate=('Flight Status', lambda x: (x != 'Completed').mean() * 100)
).reset_index()

display(crop_summary)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set_theme(style='whitegrid')

# Ensure util_df exists
util_df = df.copy()
util_df['payload_utilization'] = (
    util_df['Actual Carry Weight (kg)'] / util_df['Max Carry Weight (kg)']
) * 100

# ---------------------------------------------------------
# 1A. Scatter of utilization by drone model (shows missions are confounded)
# ---------------------------------------------------------
plt.figure(figsize=(14, 6))
order = (
    util_df.groupby('Drone Model')['payload_utilization']
    .median().sort_values().index
)
sns.stripplot(
    data=util_df,
    x='payload_utilization',
    y='Drone Model',
    order=order,
    size=6,
    alpha=0.6,
    palette='viridis'
)
plt.axvline(75, color='red', linestyle='--', label='Safe limit (75%)')
plt.axvline(100, color='black', linestyle='--', label='Hard limit (100%)')
plt.title('Payload Utilization is Bimodal by Drone Model\n(Not a Continuous Range — Reveals Confounding)')
plt.xlabel('Payload Utilization (%)')
plt.legend()
plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# 2A. Battery vs Utilization, faceted by drone model
#     Only models with enough variation in utilization
# ---------------------------------------------------------
# Keep only models with at least 5 flights and some spread
model_counts = util_df['Drone Model'].value_counts()
model_spread = util_df.groupby('Drone Model')['payload_utilization'].std()
valid_models = model_counts[(model_counts >= 5) & (model_spread > 5)].index.tolist()

facet_df = util_df[util_df['Drone Model'].isin(valid_models)].copy()

g = sns.FacetGrid(
    facet_df, col='Drone Model', col_wrap=3,
    height=3.5, sharex=False, sharey=True
)
g.map_dataframe(
    sns.regplot, x='payload_utilization', y='Battery Remaining (%)',
    scatter_kws={'alpha': 0.5, 's': 25}, line_kws={'color': 'red'}
)
g.set_titles('{col_name}')
g.set_axis_labels('Payload Utilization (%)', 'Battery Remaining (%)')
g.fig.suptitle(
    'Within Each Drone Model, Higher Utilization → Lower Battery',
    y=1.02
)
plt.tight_layout()
plt.show()
# ---------------------------------------------------------
# 2B. The "clean" summary — within-model standardized effect
# ---------------------------------------------------------
within_model_results = []

for model, group in facet_df.groupby('Drone Model'):
    g = group[['payload_utilization', 'Battery Remaining (%)']].dropna()
    if len(g) > 5 and g['payload_utilization'].std() > 0:
        r, p = stats.pearsonr(g['payload_utilization'], g['Battery Remaining (%)'])
        within_model_results.append({
            'Drone Model': model,
            'n': len(g),
            'correlation': r,
            'p_value': p
        })

within_df = pd.DataFrame(within_model_results).sort_values('correlation')

plt.figure(figsize=(10, 4))
colors = ['red' if p < 0.05 else 'gray' for p in within_df['p_value']]
plt.barh(within_df['Drone Model'], within_df['correlation'], color=colors)
plt.axvline(0, color='black', linewidth=0.8)
plt.title('Within-Model Correlation: Payload Utilization vs Battery\n(Red = statistically significant at p < 0.05)')
plt.xlabel('Pearson r')
plt.tight_layout()
plt.show()

display(within_df)

# ---------------------------------------------------------
# 5A. Failure rate with sample size annotations
# ---------------------------------------------------------
summary = (
    util_df.dropna(subset=['util_bin'])
    .groupby('util_bin', observed=False)
    .agg(
        n=('Flight Status', 'size'),
        failure_rate=('Flight Status', lambda x: (x != 'Completed').mean() * 100)
    )
    .reset_index()
)

plt.figure(figsize=(9, 5))
bars = plt.bar(
    summary['util_bin'].astype(str),
    summary['failure_rate'],
    color=['#4daf4a' if r == 0 else '#e41a1c' for r in summary['failure_rate']],
    edgecolor='black'
)
for bar, n in zip(bars, summary['n']):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1.5,
        f'n={n}',
        ha='center', fontsize=10
    )
plt.ylim(0, 110)
plt.title('Failure Rate by Payload Utilization\n(with sample size — note tiny n for overweight flights)')
plt.xlabel('Payload Utilization Bin')
plt.ylabel('Failure Rate (%)')
plt.tight_layout()
plt.show()

display(summary)

# ---------------------------------------------------------
# 6A. 3-panel composite: confounding → within-model → hard limit
# ---------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(20, 5.5))

# Panel 1: Confounding
sns.stripplot(
    data=util_df, x='payload_utilization', y='Drone Model',
    ax=axes[0], size=5, alpha=0.6, palette='viridis'
)
axes[0].axvline(100, color='black', linestyle='--')
axes[0].set_title('1. Utilization is confounded by drone model')
axes[0].set_xlabel('Payload Utilization (%)')

# Panel 2: Within-model effect
axes[1].scatter(
    within_df['correlation'], within_df['Drone Model'],
    c=['red' if p < 0.05 else 'gray' for p in within_df['p_value']],
    s=100, edgecolor='black'
)
axes[1].axvline(0, color='black', linewidth=0.8)
axes[1].set_title('2. Within-model correlation with battery')
axes[1].set_xlabel('Pearson r (utilization vs battery)')

# Panel 3: Hard limit
sns.scatterplot(
    data=util_df.dropna(subset=['payload_utilization', 'Battery Remaining (%)']),
    x='payload_utilization', y='Battery Remaining (%)',
    hue='Flight Status',
    palette={'Completed': 'steelblue', 'Aborted': 'red',
             'Landed Unexpectedly': 'orange'},
    s=60, alpha=0.7, ax=axes[2]
)
axes[2].axvline(100, color='black', linestyle='--')
axes[2].fill_betweenx([0, 100], 100, 130, color='red', alpha=0.1)
axes[2].set_title('3. Overweight flights always fail')
axes[2].set_xlabel('Payload Utilization (%)')

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

sns.set_theme(style='whitegrid')

# Use completed flights with valid duration and battery
crash_df = df[
    (df['Flight Status'] == 'Completed') &
    df['Flight Duration (minutes)'].notna() &
    df['Battery Remaining (%)'].notna()
].copy()

# Fit per model
results = []
for model, g in crash_df.groupby('Drone Model'):
    g = g[['Flight Duration (minutes)', 'Battery Remaining (%)']].dropna()
    if len(g) < 5:
        continue
    slope, intercept, r, p, se = stats.linregress(
        g['Flight Duration (minutes)'],
        g['Battery Remaining (%)']
    )
    # If slope >= 0, drone isn't draining — skip
    if slope >= 0:
        continue
    # Predicted time to reach thresholds
    t_10 = (10 - intercept) / slope
    t_0  = (0 - intercept) / slope
    # Observed max duration for extrapolation warning
    t_obs_max = g['Flight Duration (minutes)'].max()

    results.append({
        'Drone Model': model,
        'n': len(g),
        'slope_pct_per_min': slope,
        'intercept': intercept,
        'r_squared': r**2,
        'p_value': p,
        't_to_10pct': t_10,
        't_to_0pct': t_0,
        'observed_max_duration': t_obs_max,
        'extrapolation_ratio': t_0 / t_obs_max
    })

crash_table = pd.DataFrame(results).sort_values('t_to_0pct')
display(crash_table.round(2))

fig, ax = plt.subplots(figsize=(14, 8))

palette = sns.color_palette('tab20', n_colors=len(crash_table))
color_map = dict(zip(crash_table['Drone Model'], palette))

# Plot raw scatter faintly
for model, g in crash_df.groupby('Drone Model'):
    if model not in color_map:
        continue
    ax.scatter(
        g['Flight Duration (minutes)'],
        g['Battery Remaining (%)'],
        color=color_map[model], alpha=0.25, s=20
    )

# Plot extrapolated lines per model
x_max_plot = crash_table['t_to_0pct'].max() * 1.05

for _, row in crash_table.iterrows():
    x_line = np.linspace(0, min(row['t_to_0pct'] * 1.1, x_max_plot), 100)
    y_line = row['intercept'] + row['slope_pct_per_min'] * x_line
    # Only plot where y is in a sensible range
    mask = (y_line >= -5) & (y_line <= 110)
    ax.plot(
        x_line[mask], y_line[mask],
        color=color_map[row['Drone Model']],
        linewidth=2.5,
        label=f"{row['Drone Model']} (→0% at {row['t_to_0pct']:.0f} min)"
    )
    # Mark the crash point
    if row['t_to_0pct'] <= x_max_plot:
        ax.scatter(
            row['t_to_0pct'], 0,
            color=color_map[row['Drone Model']],
            marker='X', s=200, edgecolor='black', zorder=5
        )

# Threshold lines
ax.axhline(10, color='orange', linestyle='--', linewidth=1.5, label='10% reserve (safe landing)')
ax.axhline(0, color='red', linestyle='--', linewidth=1.5, label='0% (crash / forced landing)')
ax.axhspan(-5, 0, color='red', alpha=0.1)
ax.axhspan(0, 10, color='orange', alpha=0.08)

ax.set_xlim(0, x_max_plot)
ax.set_ylim(-5, 105)
ax.set_xlabel('Flight Duration (minutes)')
ax.set_ylabel('Battery Remaining (%)')
ax.set_title('Predicted Battery Depletion by Drone Model\n(Extrapolated from completed flights — dashed lines are projections)')
ax.legend(bbox_to_anchor=(1.02, 1), loc='upper left', fontsize=9)
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(12, 7))

colors = ['#e41a1c' if r > 2.0 else '#ff7f00' if r > 1.5 else '#4daf4a'
          for r in crash_table['extrapolation_ratio']]

bars = ax.barh(
    crash_table['Drone Model'],
    crash_table['t_to_0pct'],
    color=colors, edgecolor='black'
)

# Add markers for observed max
for i, (_, row) in enumerate(crash_table.iterrows()):
    ax.scatter(row['observed_max_duration'], i,
               color='black', marker='|', s=400, linewidth=3,
               label='Observed max duration' if i == 0 else '')
    ax.scatter(row['t_to_10pct'], i,
               color='orange', marker='D', s=60,
               label='Time to 10% battery' if i == 0 else '', zorder=5)

ax.axvline(30, color='gray', linestyle=':', alpha=0.5)
ax.set_xlabel('Predicted Flight Duration (minutes)')
ax.set_title('Predicted Time to Battery Depletion (0%) by Drone Model\n'
             'Colors: green = reliable extrapolation, orange/red = speculative')
ax.legend(loc='lower right')
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(12, 7))

# Sort by predicted crash time
crash_sorted = crash_table.sort_values('t_to_0pct').reset_index(drop=True)

for i, row in crash_sorted.iterrows():
    # Reliable region: up to observed max
    ax.plot([0, row['observed_max_duration']], [i, i],
            color='steelblue', linewidth=8, alpha=0.9, solid_capstyle='butt')

    # Speculative region: from observed max to predicted 0%
    ax.plot([row['observed_max_duration'], row['t_to_0pct']], [i, i],
            color='lightcoral', linewidth=8, alpha=0.6,
            linestyle=(0, (3, 3)), solid_capstyle='butt')

    # Mark predicted crash
    ax.scatter(row['t_to_0pct'], i, marker='X', s=180,
               color='darkred', edgecolor='black', zorder=5)

    # Annotate ratios
    ax.text(row['t_to_0pct'] + 3, i,
            f"{row['t_to_0pct']:.0f} min  (extrap ×{row['extrapolation_ratio']:.1f})",
            va='center', fontsize=9)

ax.set_yticks(range(len(crash_sorted)))
ax.set_yticklabels(crash_sorted['Drone Model'])
ax.set_xlabel('Flight Duration (minutes)')
ax.set_title('Predicted Battery Depletion with Extrapolation Confidence\n'
             'Blue = within observed data | Red dashed = extrapolated beyond it')

# Legend
from matplotlib.patches import Patch
legend_elems = [
    Patch(facecolor='steelblue', label='Observed flight range'),
    Patch(facecolor='lightcoral', alpha=0.6, label='Extrapolated region'),
    plt.Line2D([0], [0], marker='X', color='w',
               markerfacecolor='darkred', markeredgecolor='black',
               markersize=12, label='Predicted crash point (0%)')
]
ax.legend(handles=legend_elems, loc='lower right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

fig, ax = plt.subplots(figsize=(14, 7))

palette = sns.color_palette('tab10', n_colors=len(crash_table))
color_map = dict(zip(crash_table['Drone Model'], palette))

for _, row in crash_table.iterrows():
    # Only plot up to 2x observed max duration
    horizon = row['observed_max_duration'] * 2
    x_line = np.linspace(0, horizon, 100)
    y_line = row['intercept'] + row['slope_pct_per_min'] * x_line

    # Solid line within observed range
    x_obs = np.linspace(0, row['observed_max_duration'], 50)
    y_obs = row['intercept'] + row['slope_pct_per_min'] * x_obs
    ax.plot(x_obs, y_obs, color=color_map[row['Drone Model']], linewidth=2.5,
            label=row['Drone Model'])

    # Dashed line in extrapolated region
    x_ext = np.linspace(row['observed_max_duration'], horizon, 50)
    y_ext = row['intercept'] + row['slope_pct_per_min'] * x_ext
    ax.plot(x_ext, y_ext, color=color_map[row['Drone Model']],
            linewidth=2, linestyle='--', alpha=0.6)

    # Annotate the 10% crossing if within horizon
    t_10 = (10 - row['intercept']) / row['slope_pct_per_min']
    if t_10 <= horizon:
        ax.scatter(t_10, 10, marker='D', s=100,
                   color=color_map[row['Drone Model']],
                   edgecolor='black', zorder=5)

ax.axhline(10, color='orange', linestyle='--', label='10% reserve threshold')
ax.axhline(0, color='red', linestyle='--', label='0% (forced landing)')
ax.set_xlim(0, 100)
ax.set_ylim(-5, 105)
ax.set_xlabel('Flight Duration (minutes)')
ax.set_ylabel('Battery Remaining (%)')
ax.set_title('Predicted Battery Depletion — Realistic Horizon (≤2× Observed)\n'
             'Solid = within observed data | Dashed = extrapolated, treat with caution')
ax.legend(loc='upper right', fontsize=9)
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

features = [
    'Flight Duration (minutes)',
    'Distance Flown (km)',
    'Actual Carry Weight (kg)',
    'Altitude (meters)',
    'Wind Speed (m/s)',
    'payload_utilization'
]

model_df = analysis.copy()
model_df['payload_utilization'] = (
    model_df['Actual Carry Weight (kg)'] / model_df['Max Carry Weight (kg)']
) * 100

X = pd.get_dummies(model_df[features + ['Drone Model']], drop_first=True)
y = model_df['Battery Remaining (%)']
mask = X.notna().all(axis=1) & y.notna()
X, y = X[mask], y[mask]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(n_estimators=500, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
pred = rf.predict(X_test)

print(f"R² = {r2_score(y_test, pred):.3f}")
print(f"MAE = {mean_absolute_error(y_test, pred):.2f} percentage points")

# Actual vs predicted
fig, ax = plt.subplots(figsize=(7, 7))
ax.scatter(y_test, pred, alpha=0.6, edgecolor='black')
ax.plot([0, 100], [0, 100], 'r--', label='Perfect prediction')
ax.set_xlabel('Actual Battery Remaining (%)')
ax.set_ylabel('Predicted Battery Remaining (%)')
ax.set_title(f'Random Forest: Actual vs Predicted\nR² = {r2_score(y_test, pred):.3f}')
ax.legend()
plt.tight_layout()
plt.show()